/* ETCS DMI Symbol Catalogue — data extracted from ERA_ERTMS_015560 v4.0.0
   (ETCS Driver Machine Interface), chapters 5, 8, 13 and 14.
   Source: https://www.era.europa.eu/era-folder/1-ccs-tsi-appendix-mandatory-specifications-etcs-b4-r1-rmr-gsm-r-b1-mr1-frmcs-b0-ato-b1 */

"use strict";

const CATEGORIES = [
  { id: "level",  label: "Level",                folder: "Level",                blurb: "Current ERTMS/ETCS level and level announcements (areas C8 and C1). Spec chapter 13.2, display rules 8.2.3.2." },
  { id: "mode",   label: "Mode",                 folder: "Mode",                 blurb: "Current ETCS mode (area B7), mode acknowledgements (C1) and the override indicator (C7). Spec chapter 13.3, display rules 8.2.3.1." },
  { id: "status", label: "Status",               folder: "Status",               blurb: "Brake intervention, adhesion factor, radio connection, hour glass, reversing and BMM inhibition. Spec chapter 13.4." },
  { id: "tc",     label: "Track Conditions",     folder: "Track Conditions",     blurb: "Orders and announcements of track conditions shown at the bottom of the speed dial (B3/B4/B5, filled left to right) and tunnel stopping areas (C2–C4). Grey = automatic execution / state information, yellow = driver is requested to act. Spec chapter 13.5, rules 8.2.3.5/8.2.3.6." },
  { id: "pl",     label: "Planning",             folder: "Planning",             blurb: "Forthcoming orders/announcements (columns D2/D3/D4) and speed profile discontinuities (D6/D7) in the planning area, shown within the movement authority up to the first zero-speed target. Spec chapter 13.6, rules 8.3.4/8.3.6." },
  { id: "na",     label: "Navigation",           folder: "Navigation",           blurb: "Window navigation buttons: close, next/previous, scroll, scale, enter, delete, more. Dark grey variants = disabled state. Spec chapter 13.7, rules 5.3.2.7." },
  { id: "se",     label: "Setting",              folder: "Setting",              blurb: "Buttons of the Settings window: luminance, volume, language, and the Settings menu button itself. Spec chapter 13.8." },
  { id: "dr",     label: "Driver Request",       folder: "Driver Request",       blurb: "Buttons/objects with which the driver requests or toggles information: speed/distance toggle, Track Ahead Free, geographical position, acknowledgement, tunnel stopping area toggle. Spec chapter 13.9." },
  { id: "lx",     label: "Level Crossing",       folder: "Level Crossing",       blurb: "Level crossing not protected indication. Spec chapter 13.10, rules 8.2.3.8." },
  { id: "ls",     label: "Limited Supervision",  folder: "Limited Supervision",  blurb: "The Limited Supervision speed frame shown under the LSSMA value. Spec chapter 13.11, rules 8.2.1.7." },
  { id: "ato",    label: "ATO",                  folder: "ATO",                  blurb: "Automatic Train Operation: ATO status (G1), stopping accuracy (G2), dwell time / train hold (G3), doors (G4), skip stopping point (G5), coasting advice (B8) and stopping points in the planning area. Spec chapter 13.12, rules 8.5." },
  { id: "sm",     label: "Supervised Manoeuvre", folder: "Supervised Manoeuvre", blurb: "Authorised movement direction during Supervised Manoeuvre, shown in B8 together with mode symbol MO24. Spec chapter 13.13, rules 8.2.3.10." }
];

/* DMI grid geometry (touch screen layout, 640 x 480 cells) per chapter 6.3.
   Each entry: [x, y, w, h]. Used to highlight areas on the schematic map. */
const AREA_RECTS = {
  A1: [0, 15, 54, 54],   A2: [0, 69, 54, 30],   A3: [0, 99, 54, 191],  A4: [0, 290, 54, 25],
  B0: [54, 15, 280, 300], B1: [169, 140, 50, 50], B2: [54, 15, 280, 300],
  B3: [176, 271, 36, 36], B4: [212, 271, 36, 36], B5: [248, 271, 36, 36],
  B6: [62, 271, 36, 36],  B7: [290, 271, 36, 36], B8: [176, 213, 36, 36],
  C8: [0, 315, 54, 25],  C9: [0, 340, 54, 25],
  C2: [54, 315, 37, 50], C3: [91, 315, 37, 50], C4: [128, 315, 37, 50],
  C1: [165, 315, 58, 50],
  C5: [223, 315, 37, 50], C6: [260, 315, 37, 50], C7: [297, 315, 37, 50],
  D9: [334, 15, 40, 15], D10: [374, 15, 166, 15], D11: [540, 15, 40, 15],
  D1: [334, 30, 40, 270], D2: [374, 30, 25, 270], D3: [399, 30, 25, 270], D4: [424, 30, 25, 270],
  D5: [449, 30, 18, 270], D6: [467, 30, 14, 270], D7: [481, 30, 93, 270], D8: [574, 30, 6, 270],
  D12: [334, 300, 40, 15], D13: [374, 300, 166, 15], D14: [540, 300, 40, 15],
  D:  [334, 15, 246, 300],
  E1: [0, 365, 54, 25],  E2: [0, 390, 54, 25],  E3: [0, 415, 54, 25],  E4: [0, 440, 54, 25],
  E5: [54, 365, 234, 20], E6: [54, 385, 234, 20], E7: [54, 405, 234, 20], E8: [54, 425, 234, 20], E9: [54, 445, 234, 20],
  E10: [288, 365, 46, 50], E11: [288, 415, 46, 50],
  F1: [580, 15, 60, 50], F2: [580, 65, 60, 50], F3: [580, 115, 60, 50], F4: [580, 165, 60, 50],
  F5: [580, 215, 60, 50], F6: [580, 265, 60, 50], F7: [580, 315, 60, 50], F8: [580, 365, 60, 50],
  F9: [580, 415, 60, 50],
  G1: [334, 315, 49, 50], G2: [383, 315, 49, 50], G3: [432, 315, 49, 50], G4: [481, 315, 49, 50], G5: [530, 315, 50, 50],
  G6: [334, 365, 49, 50], G7: [383, 365, 49, 50], G8: [432, 365, 49, 50], G9: [481, 365, 49, 50], G10: [530, 365, 50, 50],
  G11: [334, 415, 63, 50], G12: [397, 415, 120, 50], G13: [517, 415, 63, 50]
};

/* What the main DMI areas are for (used in the detail view + map legend). */
const AREA_INFO = {
  A1: "Distance to target / LSSMA area (top left)",
  A4: "Adhesion factor area (bottom of column A)",
  B0: "Speedometer (speed dial)",
  "B3": "Track condition slot 1 (under the speed dial)",
  "B4": "Track condition slot 2 (under the speed dial)",
  "B5": "Track condition slot 3 (under the speed dial)",
  B6: "Release speed area",
  B7: "Current mode symbol (bottom right of the speed dial)",
  B8: "Coasting advice / SM direction (above B4)",
  C1: "Acknowledgement area (mode/level announcements)",
  C2: "Tunnel stopping area symbol", C3: "Tunnel stopping area distance", C4: "Tunnel stopping area distance",
  C6: "Reversing permitted / BMM inhibition",
  C7: "Override (EOA) indicator",
  C8: "Current ERTMS/ETCS level",
  C9: "Brake intervention indicator",
  D: "Planning area",
  D2: "Planning: order/announcement column 1", D3: "Planning: order/announcement column 2", D4: "Planning: order/announcement column 3",
  D6: "Planning: speed discontinuity (left half)", D7: "Planning: speed discontinuity / PASP (right half)",
  D9: "Planning zoom: scale up button", D12: "Planning zoom: scale down button",
  E1: "Safe radio connection indicator",
  E5: "Text message line 1", E6: "Text message line 2", E7: "Text message line 3", E8: "Text message line 4", E9: "Text message line 5",
  E10: "Text messages: scroll up", E11: "Text messages: scroll down",
  F5: "Button area F5", F6: "Button area F6", F7: "Button area F7", F8: "Button area F8", F9: "Button area F9", F10: "Button area F10 (soft key)",
  G1: "ATO status / engage button", G2: "ATO stopping accuracy", G3: "ATO dwell time / train hold", G4: "ATO door information", G5: "ATO skip stopping point",
  G12: "Geographical position", G13: "Local time",
  H2: "Soft key H2", H3: "Soft key H3", H4: "Soft key H4", H5: "Soft key H5", H6: "Soft key H6", H7: "Soft key H7 (acknowledge/enter)"
};

/* Sounds — chapter 14. */
const SOUNDS = [
  { file: "click.wav", name: "Click", spec: "S_click", when: "Feedback while pressing the finger on a DMI button. Played once per press.", ref: "14.2.1" },
  { file: "S_info.wav", name: "Sinfo — Information", spec: "S_info", when: "Draws the driver's attention to new visual information on the DMI, e.g. a new text message of the first group, the Time-To-Indication display (except in Automatic Driving mode), or a change of the Supervised Manoeuvre authorised direction. Played once.", ref: "14.3.1" },
  { file: "S1_toofast.wav", name: "S1 — Over-speed", spec: "S1_toofast", when: "The current train speed/position has exceeded the Permitted supervision limit (P) in Target Speed Monitoring — the Over-speed status is activated. Played once.", ref: "14.3.2" },
  { file: "S2_warning.wav", name: "S2 — Warning", spec: "S2_warning", when: "The current train speed/position is close to the Service Brake Intervention supervision limit (SBI) — the Warning status is activated. Played repeatedly as long as the Warning status is active.", ref: "14.3.3" }
];

/* Helper shorthands used while building the symbol list. */
const TC_GROUP_WHEN = "Shown while the corresponding track condition is active or announced at the current train position (per SRS, document [2]). Symbols fill areas B3, B4, B5 from left to right; if all three slots are occupied, further symbols wait until a slot is free.";
const PL_GROUP_WHEN = "Shown in the planning area columns D2/D3/D4 at the (scaled) distance where the order/announcement will take effect — within the movement authority and up to the first zero-speed target.";

const SYMBOLS = [
  /* ============ LEVEL (Table 59) ============ */
  { id: "LE01", cat: "level", file: "LE_01.png", name: "Level 0", color: "grey", size: "52×21", areas: ["C8"],
    when: "Shown while the current ERTMS/ETCS level is 0 and valid. If the current level is unknown or invalid, nothing is displayed in C8.", ref: "8.2.3.2.2, 8.2.3.2.4" },
  { id: "LE02", cat: "level", file: "LE_02.png", extra: ["LE_02a.png"], name: "Level NTC", color: "grey", size: "52×21", areas: ["C8"],
    remarks: "The text “NTC” is replaced by the distinct abbreviation of the corresponding National System (see example bitmap LE_02a).",
    when: "Shown while the current level is NTC (except in modes SN and NL). In level NTC the exact display location is not specified by the spec.", ref: "8.2.3.2.2, 8.2.3.2.9" },
  { id: "LE03", cat: "level", file: "LE_03.png", name: "Level 1 (intermittent transmission)", color: "grey", size: "52×21", areas: ["C8"],
    when: "Shown while the current ERTMS/ETCS level is 1 and valid.", ref: "8.2.3.2.2, 8.2.3.2.4" },
  { id: "LE04", cat: "level", file: "LE_04.png", name: "Level 2 (continuous transmission)", color: "grey", size: "52×21", areas: ["C8"],
    when: "Shown while the current ERTMS/ETCS level is 2 and valid.", ref: "8.2.3.2.2, 8.2.3.2.4" },
  { id: "LE06", cat: "level", file: "LE_06.png", name: "Level 0 announcement", color: "grey", size: "52×21", areas: ["C1"],
    when: "A transition to level 0 is announced and no acknowledgement is (yet) required — i.e. either no acknowledgement is needed at all, the train has not yet reached the location from which acknowledgement is required, or the driver has already acknowledged (then it replaces LE07). Suppressed while a mode acknowledgement is shown in C1.", ref: "8.2.3.2.7, 8.2.3.2.8" },
  { id: "LE07", cat: "level", file: "LE_07.png", name: "Level 0 announcement — acknowledgement", color: "yellow", size: "52×21", areas: ["C1"],
    remarks: "Always with a flashing frame.",
    when: "A transition to level 0 is announced, acknowledgement is required and the train has reached the location from which the driver must acknowledge. After acknowledgement it is replaced by LE06.", ref: "8.2.3.2.8" },
  { id: "LE08", cat: "level", file: "LE_08.png", extra: ["LE_08a.png"], name: "Level NTC announcement", color: "grey", size: "52×21", areas: ["C1"],
    remarks: "“NTC” is replaced by the National System abbreviation (example bitmap LE_08a).",
    when: "A transition to level NTC is announced without (or before/after) a required acknowledgement, analogous to LE06.", ref: "8.2.3.2.7, 8.2.3.2.8" },
  { id: "LE09", cat: "level", file: "LE_09.png", extra: ["LE_09a.png"], name: "Level NTC announcement — acknowledgement", color: "yellow", size: "52×21", areas: ["C1"],
    remarks: "Always with a flashing frame. “NTC” is replaced by the National System abbreviation (example bitmap LE_09a).",
    when: "A transition to level NTC is announced, acknowledgement is required and the train is inside the acknowledgement area. Replaced by LE08 after acknowledgement.", ref: "8.2.3.2.8" },
  { id: "LE10", cat: "level", file: "LE_10.png", name: "Level 1 announcement", color: "grey", size: "52×21", areas: ["C1"],
    when: "A transition to level 1 is announced (no acknowledgement variant exists for level 1 in v4.0.0).", ref: "8.2.3.2.7" },
  { id: "LE11", cat: "level", file: "LE_11.png", name: "Level 1 announcement — acknowledgement (legacy)", color: "yellow", size: "52×21", areas: ["C1"], legacy: true,
    remarks: "This bitmap ships in the official symbol set but is not referenced anywhere in ERA_ERTMS_015560 v4.0.0 — in v4.0.0 only level 0 (LE07) and level NTC (LE09) announcements can require acknowledgement. It stems from earlier baselines.",
    when: "Not used in DMI v4.0.0.", ref: "—" },
  { id: "LE12", cat: "level", file: "LE_12.png", name: "Level 2 announcement", color: "grey", size: "52×21", areas: ["C1"],
    when: "A transition to level 2 is announced (no acknowledgement variant exists for level 2 in v4.0.0).", ref: "8.2.3.2.7" },

  /* ============ MODE (Table 60) ============ */
  { id: "MO01", cat: "mode", file: "MO_01.png", name: "Shunting (SH)", color: "grey", size: "32×32", areas: ["B7"],
    when: "Shown while the on-board is in Shunting mode — selected by the driver or ordered by trackside.", ref: "8.2.3.1.2" },
  { id: "MO02", cat: "mode", file: "MO_02.png", name: "Acknowledgement for Shunting", color: "yellow", size: "32×32", areas: ["C1"],
    remarks: "Always with a flashing frame.",
    when: "Trackside orders a transition to Shunting mode and the driver must acknowledge it. Replaces any level announcement in C1 until acknowledged.", ref: "8.2.3.1.3, 8.2.3.1.6" },
  { id: "MO03", cat: "mode", file: "MO_03.png", name: "Override EOA active", color: "grey", size: "32×32", areas: ["C7"],
    when: "Shown as long as the override function is active, i.e. after the driver pressed the Override (EOA) button and until the override conditions end (per SRS).", ref: "8.2.3.1.5, 8.2.3.1.9" },
  { id: "MO04", cat: "mode", file: "MO_04.png", name: "Trip (TR)", color: "red with grey", size: "32×32", areas: ["B7"],
    when: "Shown while the on-board is in Trip mode — the train was tripped (e.g. passed the EOA without authority); the emergency brake is commanded (see ST01).", ref: "8.2.3.1.2" },
  { id: "MO05", cat: "mode", file: "MO_05.png", name: "Acknowledgement for Trip", color: "yellow", size: "32×32", areas: ["C1"],
    remarks: "Always with a flashing frame.",
    when: "Shown at standstill after a trip; the driver must acknowledge the trip, after which the on-board switches to Post Trip mode.", ref: "8.2.3.1.3, 11.7 (S7)" },
  { id: "MO06", cat: "mode", file: "MO_06.png", name: "Post Trip (PT)", color: "grey", size: "32×32", areas: ["B7"],
    when: "Shown while the on-board is in Post Trip mode (after the driver acknowledged a trip).", ref: "8.2.3.1.2" },
  { id: "MO07", cat: "mode", file: "MO_07.png", name: "On Sight (OS)", color: "grey", size: "32×32", areas: ["B7"],
    when: "Shown while the on-board is in On Sight mode.", ref: "8.2.3.1.2" },
  { id: "MO08", cat: "mode", file: "MO_08.png", name: "Acknowledgement for On Sight", color: "yellow", size: "32×32", areas: ["C1"],
    remarks: "Always with a flashing frame.",
    when: "Entry into On Sight mode requires the driver's acknowledgement.", ref: "8.2.3.1.3" },
  { id: "MO09", cat: "mode", file: "MO_09.png", name: "Staff Responsible (SR)", color: "grey", size: "32×32", areas: ["B7"],
    when: "Shown while the on-board is in Staff Responsible mode.", ref: "8.2.3.1.2" },
  { id: "MO10", cat: "mode", file: "MO_10.png", name: "Acknowledgement for Staff Responsible", color: "yellow", size: "46×46", areas: ["C1"],
    remarks: "Always with a flashing frame. The acknowledgement button is a delay-type button (must be held ~2 s).",
    when: "Entry into Staff Responsible mode requires the driver's acknowledgement (e.g. when starting under SR or after override).", ref: "8.2.3.1.3, 8.2.3.1.4" },
  { id: "MO11", cat: "mode", file: "MO_11.png", name: "Full Supervision (FS)", color: "grey", size: "32×32", areas: ["B7"],
    when: "Shown while the on-board is in Full Supervision mode — complete train and track data available, full speed/distance supervision.", ref: "8.2.3.1.2" },
  { id: "MO12", cat: "mode", file: "MO_12.png", name: "Non-Leading (NL)", color: "grey", size: "32×32", areas: ["B7"],
    when: "Shown while the engine is in Non-Leading mode (slave engine of a consist, not leading).", ref: "8.2.3.1.2" },
  { id: "MO13", cat: "mode", file: "MO_13.png", name: "Stand By (SB)", color: "grey", size: "32×32", areas: ["B7"],
    when: "Shown while the on-board is in Stand By mode (default mode after start-up, before start of mission).", ref: "8.2.3.1.2" },
  { id: "MO14", cat: "mode", file: "MO_14.png", name: "Reversing (RV)", color: "grey", size: "32×32", areas: ["B7"],
    when: "Shown while the on-board is in Reversing mode (moving in the opposite direction inside a reversing area, e.g. emergency evacuation).", ref: "8.2.3.1.2" },
  { id: "MO15", cat: "mode", file: "MO_15.png", name: "Acknowledgement for Reversing", color: "yellow", size: "32×32", areas: ["C1"],
    remarks: "Always with a flashing frame.",
    when: "Entry into Reversing mode requires the driver's acknowledgement (train at standstill inside a reversing area, see also ST06).", ref: "8.2.3.1.3" },
  { id: "MO16", cat: "mode", file: "MO_16.png", name: "Unfitted (UN)", color: "grey", size: "32×32", areas: ["B7"],
    when: "Shown while the on-board is in Unfitted mode (running on a line without ETCS/national train protection, level 0).", ref: "8.2.3.1.2" },
  { id: "MO17", cat: "mode", file: "MO_17.png", name: "Acknowledgement for Unfitted", color: "yellow", size: "32×32", areas: ["C1"],
    remarks: "Always with a flashing frame.",
    when: "Entry into Unfitted mode requires the driver's acknowledgement (e.g. on a level transition to level 0).", ref: "8.2.3.1.3" },
  { id: "MO18", cat: "mode", file: "MO_18.png", name: "System Failure (SF)", color: "red with grey", size: "32×32", areas: ["B7"],
    remarks: "If MO18 cannot be displayed at all (display failure), SF mode is indicated by other means — blank/frozen screen, dedicated lamp, sound, …",
    when: "Shown when the on-board equipment has a fault affecting safety — emergency brake is commanded.", ref: "8.2.3.1.2, 8.2.3.1.2.1" },
  { id: "MO19", cat: "mode", file: "MO_19.png", name: "National System (SN)", color: "grey", size: "32×32", areas: [],
    areaText: "In level NTC the location is not specified",
    when: "Shown while the on-board is in SN mode (national train protection system in charge, level NTC). The display location is up to the national system integration.", ref: "8.2.3.1.2" },
  { id: "MO20", cat: "mode", file: "MO_20.png", name: "Acknowledgement for National System", color: "yellow", size: "32×32", areas: ["C1"],
    remarks: "Always with a flashing frame.",
    when: "Entry into SN mode (level NTC transition) requires the driver's acknowledgement.", ref: "8.2.3.1.3" },
  { id: "MO21", cat: "mode", file: "MO_21.png", name: "Limited Supervision (LS)", color: "grey", size: "32×32", areas: ["B7"],
    when: "Shown while the on-board is in Limited Supervision mode (background supervision; line-side signals remain the reference — see also LS01/LSSMA).", ref: "8.2.3.1.2" },
  { id: "MO22", cat: "mode", file: "MO_22.png", name: "Acknowledgement for Limited Supervision", color: "yellow", size: "32×32", areas: ["C1"],
    remarks: "Always with a flashing frame.",
    when: "Entry into Limited Supervision mode requires the driver's acknowledgement.", ref: "8.2.3.1.3" },
  { id: "MO23", cat: "mode", file: "MO_23.png", name: "Automatic Driving (AD)", color: "grey", size: "32×32", areas: ["B7"],
    when: "Shown while the on-board is in Automatic Driving mode (ATO engaged — see also ATO03 in G1).", ref: "8.2.3.1.2" },
  { id: "MO24", cat: "mode", file: "MO_24.png", name: "Supervised Manoeuvre (SM)", color: "grey", size: "32×32", areas: ["B7"],
    when: "Shown while the on-board is in Supervised Manoeuvre mode; the authorised direction (SM01/SM02) is shown in B8 at the same time.", ref: "8.2.3.1.2, 11.7 (S19)" },

  /* ============ STATUS (Table 61) ============ */
  { id: "ST01", cat: "status", file: "ST_01.png", name: "Service / emergency brake intervention", color: "red with grey", size: "52×21", areas: ["C9"],
    remarks: "Possibly with a flashing frame (when the brake intervention must be acknowledged).",
    when: "Shown while ERTMS/ETCS is commanding the service or emergency brake (over-speed intervention, trip, …). If an acknowledgement is required, the frame flashes; when the intervention is released without acknowledgement the symbol disappears.", ref: "8.2.2.3" },
  { id: "ST02", cat: "status", file: "ST_02.png", name: "Adhesion factor “slippery rail”", color: "grey", size: "52×21", areas: ["A4"],
    when: "Shown while the adhesion factor is set to “slippery rail” (by the driver via the Special menu or by trackside). Removed when adhesion returns to “non slippery rail”.", ref: "8.2.3.7, 11.7 (S15)" },
  { id: "ST03", cat: "status", file: "ST_03.png", name: "Safe radio connection “Connection Up”", color: "grey", size: "52×21", areas: ["E1"],
    when: "Shown while the indication status of the safe radio connection (to the RBC) is “Connection Up”. Nothing is shown for status “No Connection”.", ref: "8.4.1.3" },
  { id: "ST04", cat: "status", file: "ST_04.png", name: "Safe radio connection “Connection Lost / Set-Up failed”", color: "red with grey", size: "52×21", areas: ["E1"],
    when: "Shown while the indication status of the safe radio connection is “Connection Lost/Set-Up failed”.", ref: "8.4.1.5" },
  { id: "ST05", cat: "status", file: "ST_05.png", name: "Hour glass", color: "grey", size: "20×20", areas: [],
    areaText: "Window title of “Main” and “Radio data” menu windows",
    when: "Shown in the window title while the on-board is exchanging data with the RBC / awaiting an answer (e.g. after Start, SH request, train data validation, SM request). It moves to the right by one character width every second; all buttons of the window are disabled meanwhile.", ref: "11.2.1.6, 11.7" },
  { id: "ST06", cat: "status", file: "ST_06.png", name: "Reversing permitted", color: "grey", size: "32×32", areas: ["C6"],
    when: "Shown when the train is at standstill inside a reversing area — i.e. reversing (RV mode) may be initiated by moving in the opposite direction.", ref: "8.4.2.2" },
  { id: "ST07", cat: "status", file: null, name: "BMM reaction inhibition", color: "grey", size: "32×32", areas: ["C6"], missing: true,
    remarks: "Listed in Table 61 of v4.0.0, but the bitmap is not included in the published symbol folder (index006).",
    when: "Shown while the Big Metal Mass reaction inhibition is active — the driver inhibited the on-board reaction to balise transmission interferences caused by big metal masses (toggle in the Special menu). Removed when the inhibition ends.", ref: "8.2.3.11, 11.7 (S22)" },

  /* ============ TRACK CONDITIONS (Table 62) ============ */
  { id: "TC01", cat: "tc", file: "TC_01.png", name: "Pantograph lowered", color: "grey", size: "32×32", areas: ["B3","B4","B5"],
    when: "Indicates the state “pantograph is lowered” inside a lowered-pantograph section. " + TC_GROUP_WHEN, ref: "8.2.3.5.8" },
  { id: "TC02", cat: "tc", file: "TC_02.png", name: "Lower pantograph (automatic)", color: "grey", size: "32×32", areas: ["B3","B4","B5"],
    when: "Order/announcement “lower pantograph” with automatic execution by the train. " + TC_GROUP_WHEN, ref: "8.2.3.5.7" },
  { id: "TC03", cat: "tc", file: "TC_03.png", name: "Lower pantograph (driver action)", color: "yellow", size: "32×32", areas: ["B3","B4","B5"],
    when: "Order “lower pantograph” — the driver is requested to act. " + TC_GROUP_WHEN, ref: "8.2.3.5.7" },
  { id: "TC04", cat: "tc", file: "TC_04.png", name: "Raise pantograph (automatic)", color: "grey", size: "32×32", areas: ["B3","B4","B5"],
    when: "Order “raise pantograph” with automatic execution. " + TC_GROUP_WHEN, ref: "8.2.3.5.9" },
  { id: "TC05", cat: "tc", file: "TC_05.png", name: "Raise pantograph (driver action)", color: "yellow", size: "32×32", areas: ["B3","B4","B5"],
    when: "Order “raise pantograph” — the driver is requested to act. " + TC_GROUP_WHEN, ref: "8.2.3.5.9" },
  { id: "TC06", cat: "tc", file: "TC_06.png", name: "Neutral section / announcement (automatic)", color: "grey", size: "32×32", areas: ["B3","B4","B5"],
    when: "Announcement of a neutral section with automatic execution, and indication while inside the neutral section. " + TC_GROUP_WHEN, ref: "8.2.3.5.10, 8.2.3.5.11" },
  { id: "TC07", cat: "tc", file: "TC_07.png", name: "Neutral section announcement (driver action)", color: "yellow", size: "32×32", areas: ["B3","B4","B5"],
    when: "Announcement of a neutral section — the driver is requested to act (open the main power switch). " + TC_GROUP_WHEN, ref: "8.2.3.5.10" },
  { id: "TC08", cat: "tc", file: "TC_08.png", name: "End of neutral section (automatic)", color: "grey", size: "32×32", areas: ["B3","B4","B5"],
    when: "Order “end of neutral section” with automatic execution. " + TC_GROUP_WHEN, ref: "8.2.3.5.12" },
  { id: "TC09", cat: "tc", file: "TC_09.png", name: "End of neutral section (driver action)", color: "yellow", size: "32×32", areas: ["B3","B4","B5"],
    when: "Order “end of neutral section” — the driver is requested to act (close the main power switch). " + TC_GROUP_WHEN, ref: "8.2.3.5.12" },
  { id: "TC10", cat: "tc", file: "TC_10.png", name: "Non stopping area", color: "grey", size: "32×32", areas: ["B3","B4","B5"],
    when: "Indicates the train is inside a non-stopping area (do not stop here, e.g. fire risk zone). " + TC_GROUP_WHEN, ref: "8.2.3.5.13" },
  { id: "TC11", cat: "tc", file: "TC_11.png", name: "Non stopping area announcement", color: "yellow", size: "32×32", areas: ["B3","B4","B5"],
    when: "Announcement of an approaching non-stopping area. " + TC_GROUP_WHEN, ref: "8.2.3.5.13" },
  { id: "TC12", cat: "tc", file: "TC_12.png", name: "Radio hole", color: "grey", size: "32×32", areas: ["B3","B4","B5"],
    when: "Indicates the train is inside a radio hole (announced area without radio coverage — no “connection lost” reaction expected). " + TC_GROUP_WHEN, ref: "8.2.3.5.14" },
  { id: "TC13", cat: "tc", file: "TC_13.png", name: "Inhibition of magnetic shoe brake / announcement (automatic)", color: "grey", size: "32×32", areas: ["B3","B4","B5"],
    when: "Announcement (automatic execution) and indication of “inhibition of magnetic shoe brake”. " + TC_GROUP_WHEN, ref: "8.2.3.5.15, 8.2.3.5.16" },
  { id: "TC14", cat: "tc", file: "TC_14.png", name: "Inhibition of magnetic shoe brake announcement (driver action)", color: "yellow", size: "32×32", areas: ["B3","B4","B5"],
    when: "Announcement of “inhibition of magnetic shoe brake” — the driver is requested to act. " + TC_GROUP_WHEN, ref: "8.2.3.5.15" },
  { id: "TC15", cat: "tc", file: "TC_15.png", name: "Inhibition of eddy current brake / announcement (automatic)", color: "grey", size: "32×32", areas: ["B3","B4","B5"],
    when: "Announcement (automatic execution) and indication of “inhibition of eddy current brake”. " + TC_GROUP_WHEN, ref: "8.2.3.5.17, 8.2.3.5.18" },
  { id: "TC16", cat: "tc", file: "TC_16.png", name: "Inhibition of eddy current brake announcement (driver action)", color: "yellow", size: "32×32", areas: ["B3","B4","B5"],
    when: "Announcement of “inhibition of eddy current brake” — the driver is requested to act. " + TC_GROUP_WHEN, ref: "8.2.3.5.17" },
  { id: "TC17", cat: "tc", file: "TC_17.png", name: "Inhibition of regenerative brake / announcement (automatic)", color: "grey", size: "32×32", areas: ["B3","B4","B5"],
    when: "Announcement (automatic execution) and indication of “inhibition of regenerative brake”. " + TC_GROUP_WHEN, ref: "8.2.3.5.19, 8.2.3.5.20" },
  { id: "TC18", cat: "tc", file: "TC_18.png", name: "Inhibition of regenerative brake announcement (driver action)", color: "yellow", size: "32×32", areas: ["B3","B4","B5"],
    when: "Announcement of “inhibition of regenerative brake” — the driver is requested to act. " + TC_GROUP_WHEN, ref: "8.2.3.5.19" },
  { id: "TC19", cat: "tc", file: "TC_19.png", name: "Air conditioning intake closed / close announcement (automatic)", color: "grey", size: "32×32", areas: ["B3","B4","B5"],
    when: "Announcement “close air conditioning intake” with automatic execution, and indication “air conditioning intake closed”. " + TC_GROUP_WHEN, ref: "8.2.3.5.4, 8.2.3.5.5" },
  { id: "TC20", cat: "tc", file: "TC_20.png", name: "Open air conditioning intake (automatic)", color: "grey", size: "32×32", areas: ["B3","B4","B5"],
    when: "Order “open air conditioning intake” with automatic execution. " + TC_GROUP_WHEN, ref: "8.2.3.5.6" },
  { id: "TC21", cat: "tc", file: "TC_21.png", name: "Close air conditioning intake announcement (driver action)", color: "yellow", size: "32×32", areas: ["B3","B4","B5"],
    when: "Announcement “close air conditioning intake” — the driver is requested to act. " + TC_GROUP_WHEN, ref: "8.2.3.5.4" },
  { id: "TC22", cat: "tc", file: "TC_22.png", name: "Open air conditioning intake (driver action)", color: "yellow", size: "32×32", areas: ["B3","B4","B5"],
    when: "Order “open air conditioning intake” — the driver is requested to act. " + TC_GROUP_WHEN, ref: "8.2.3.5.6" },
  { id: "TC23", cat: "tc", file: "TC_23.png", name: "Traction: no traction system / announcement (automatic)", color: "grey", size: "32×32", areas: ["B3","B4","B5"],
    when: "Change-of-traction announcement “line not fitted with any traction system” (automatic execution) and indication of the new traction state. " + TC_GROUP_WHEN, ref: "8.2.3.5.21, 8.2.3.5.22" },
  { id: "TC24", cat: "tc", file: "TC_24.png", name: "Traction: no traction system announcement (driver action)", color: "yellow", size: "32×32", areas: ["B3","B4","B5"],
    when: "Change-of-traction announcement “line not fitted with any traction system” — the driver is requested to act. " + TC_GROUP_WHEN, ref: "8.2.3.5.21" },
  { id: "TC25", cat: "tc", file: "TC_25.png", name: "Traction: AC 25 kV 50 Hz / announcement (automatic)", color: "grey", size: "32×32", areas: ["B3","B4","B5"],
    when: "Change-of-traction announcement “AC 25 kV 50 Hz” (automatic execution) and indication of the new traction system. " + TC_GROUP_WHEN, ref: "8.2.3.5.23, 8.2.3.5.24" },
  { id: "TC26", cat: "tc", file: "TC_26.png", name: "Traction: AC 25 kV 50 Hz announcement (driver action)", color: "yellow", size: "32×32", areas: ["B3","B4","B5"],
    when: "Change-of-traction announcement “AC 25 kV 50 Hz” — the driver is requested to act. " + TC_GROUP_WHEN, ref: "8.2.3.5.23" },
  { id: "TC27", cat: "tc", file: "TC_27.png", name: "Traction: AC 15 kV 16.7 Hz / announcement (automatic)", color: "grey", size: "32×32", areas: ["B3","B4","B5"],
    when: "Change-of-traction announcement “AC 15 kV 16.7 Hz” (automatic execution) and indication of the new traction system. " + TC_GROUP_WHEN, ref: "8.2.3.5.25, 8.2.3.5.26" },
  { id: "TC28", cat: "tc", file: "TC_28.png", name: "Traction: AC 15 kV 16.7 Hz announcement (driver action)", color: "yellow", size: "32×32", areas: ["B3","B4","B5"],
    when: "Change-of-traction announcement “AC 15 kV 16.7 Hz” — the driver is requested to act. " + TC_GROUP_WHEN, ref: "8.2.3.5.25" },
  { id: "TC29", cat: "tc", file: "TC_29.png", name: "Traction: DC 3 kV / announcement (automatic)", color: "grey", size: "32×32", areas: ["B3","B4","B5"],
    when: "Change-of-traction announcement “DC 3 kV” (automatic execution) and indication of the new traction system. " + TC_GROUP_WHEN, ref: "8.2.3.5.27, 8.2.3.5.28" },
  { id: "TC30", cat: "tc", file: "TC_30.png", name: "Traction: DC 3 kV announcement (driver action)", color: "yellow", size: "32×32", areas: ["B3","B4","B5"],
    when: "Change-of-traction announcement “DC 3 kV” — the driver is requested to act. " + TC_GROUP_WHEN, ref: "8.2.3.5.27" },
  { id: "TC31", cat: "tc", file: "TC_31.png", name: "Traction: DC 1.5 kV / announcement (automatic)", color: "grey", size: "32×32", areas: ["B3","B4","B5"],
    when: "Change-of-traction announcement “DC 1.5 kV” (automatic execution) and indication of the new traction system. " + TC_GROUP_WHEN, ref: "8.2.3.5.29, 8.2.3.5.30" },
  { id: "TC32", cat: "tc", file: "TC_32.png", name: "Traction: DC 1.5 kV announcement (driver action)", color: "yellow", size: "32×32", areas: ["B3","B4","B5"],
    when: "Change-of-traction announcement “DC 1.5 kV” — the driver is requested to act. " + TC_GROUP_WHEN, ref: "8.2.3.5.29" },
  { id: "TC33", cat: "tc", file: "TC_33.png", name: "Traction: DC 600/750 V / announcement (automatic)", color: "grey", size: "32×32", areas: ["B3","B4","B5"],
    when: "Change-of-traction announcement “DC 600/750 V” (automatic execution) and indication of the new traction system. " + TC_GROUP_WHEN, ref: "8.2.3.5.31, 8.2.3.5.32" },
  { id: "TC34", cat: "tc", file: "TC_34.png", name: "Traction: DC 600/750 V announcement (driver action)", color: "yellow", size: "32×32", areas: ["B3","B4","B5"],
    when: "Change-of-traction announcement “DC 600/750 V” — the driver is requested to act. " + TC_GROUP_WHEN, ref: "8.2.3.5.31" },
  { id: "TC35", cat: "tc", file: "TC_35.png", name: "Sound horn", color: "yellow", size: "32×32", areas: ["B3","B4","B5"],
    when: "Order “sound horn” — the driver must sound the horn (e.g. approaching a whistle board / level crossing). " + TC_GROUP_WHEN, ref: "8.2.3.5.33" },
  { id: "TC36", cat: "tc", file: "TC_36.png", name: "Tunnel stopping area", color: "grey", size: "32×32", areas: ["C2"],
    when: "Indicates the train is inside a tunnel stopping area (a safe place to stop in a tunnel). Only shown if tunnel stopping areas are known by the on-board and the display is toggled on (see DR05).", ref: "8.2.3.6.7" },
  { id: "TC37", cat: "tc", file: "TC_37.png", name: "Tunnel stopping area announcement", color: "yellow", size: "32×32", areas: ["C2","C3","C4"],
    when: "Announcement of the next tunnel stopping area; while displayed, the remaining distance to it (up to 5 digits, 1 m resolution) is shown next to it in C3/C4. Requires the display to be toggled on (see DR05).", ref: "8.2.3.6.7–8.2.3.6.9" },

  /* ============ PLANNING (Table 63) ============ */
  { id: "PL01", cat: "pl", file: "PL_01.png", name: "Planning: lower pantograph (automatic)", color: "grey", size: "20×20", areas: ["D2","D3","D4"],
    when: "Forthcoming order “lower pantograph”, automatic execution. " + PL_GROUP_WHEN, ref: "8.3.4.5" },
  { id: "PL02", cat: "pl", file: "PL_02.png", name: "Planning: lower pantograph (driver action)", color: "yellow", size: "20×20", areas: ["D2","D3","D4"],
    when: "Forthcoming order “lower pantograph”, driver requested to act. " + PL_GROUP_WHEN, ref: "8.3.4.5" },
  { id: "PL03", cat: "pl", file: "PL_03.png", name: "Planning: raise pantograph (automatic)", color: "grey", size: "20×20", areas: ["D2","D3","D4"],
    when: "Forthcoming order “raise pantograph”, automatic execution. " + PL_GROUP_WHEN, ref: "8.3.4.6" },
  { id: "PL04", cat: "pl", file: "PL_04.png", name: "Planning: raise pantograph (driver action)", color: "yellow", size: "20×20", areas: ["D2","D3","D4"],
    when: "Forthcoming order “raise pantograph”, driver requested to act. " + PL_GROUP_WHEN, ref: "8.3.4.6" },
  { id: "PL05", cat: "pl", file: "PL_05.png", name: "Planning: neutral section announcement (automatic)", color: "grey", size: "20×20", areas: ["D2","D3","D4"],
    when: "Forthcoming neutral section, automatic execution. " + PL_GROUP_WHEN, ref: "8.3.4.7" },
  { id: "PL06", cat: "pl", file: "PL_06.png", name: "Planning: neutral section announcement (driver action)", color: "yellow", size: "20×20", areas: ["D2","D3","D4"],
    when: "Forthcoming neutral section, driver requested to act. " + PL_GROUP_WHEN, ref: "8.3.4.7" },
  { id: "PL07", cat: "pl", file: "PL_07.png", name: "Planning: end of neutral section (automatic)", color: "grey", size: "20×20", areas: ["D2","D3","D4"],
    when: "Forthcoming end of neutral section, automatic execution. " + PL_GROUP_WHEN, ref: "8.3.4.8" },
  { id: "PL08", cat: "pl", file: "PL_08.png", name: "Planning: end of neutral section (driver action)", color: "yellow", size: "20×20", areas: ["D2","D3","D4"],
    when: "Forthcoming end of neutral section, driver requested to act. " + PL_GROUP_WHEN, ref: "8.3.4.8" },
  { id: "PL09", cat: "pl", file: "PL_09.png", name: "Planning: non stopping area announcement", color: "yellow", size: "20×20", areas: ["D2","D3","D4"],
    when: "Forthcoming non-stopping area. " + PL_GROUP_WHEN, ref: "8.3.4.9" },
  { id: "PL10", cat: "pl", file: "PL_10.png", name: "Planning: radio hole", color: "grey", size: "20×20", areas: ["D2","D3","D4"],
    when: "Forthcoming radio hole. " + PL_GROUP_WHEN, ref: "8.3.4.10" },
  { id: "PL11", cat: "pl", file: "PL_11.png", name: "Planning: inhibition of magnetic shoe brake (automatic)", color: "grey", size: "20×20", areas: ["D2","D3","D4"],
    when: "Forthcoming inhibition of magnetic shoe brake, automatic execution. " + PL_GROUP_WHEN, ref: "8.3.4.11" },
  { id: "PL12", cat: "pl", file: "PL_12.png", name: "Planning: inhibition of magnetic shoe brake (driver action)", color: "yellow", size: "20×20", areas: ["D2","D3","D4"],
    when: "Forthcoming inhibition of magnetic shoe brake, driver requested to act. " + PL_GROUP_WHEN, ref: "8.3.4.11" },
  { id: "PL13", cat: "pl", file: "PL_13.png", name: "Planning: inhibition of eddy current brake (automatic)", color: "grey", size: "20×20", areas: ["D2","D3","D4"],
    when: "Forthcoming inhibition of eddy current brake, automatic execution. " + PL_GROUP_WHEN, ref: "8.3.4.12" },
  { id: "PL14", cat: "pl", file: "PL_14.png", name: "Planning: inhibition of eddy current brake (driver action)", color: "yellow", size: "20×20", areas: ["D2","D3","D4"],
    when: "Forthcoming inhibition of eddy current brake, driver requested to act. " + PL_GROUP_WHEN, ref: "8.3.4.12" },
  { id: "PL15", cat: "pl", file: "PL_15.png", name: "Planning: inhibition of regenerative brake (automatic)", color: "grey", size: "20×20", areas: ["D2","D3","D4"],
    when: "Forthcoming inhibition of regenerative brake, automatic execution. " + PL_GROUP_WHEN, ref: "8.3.4.13" },
  { id: "PL16", cat: "pl", file: "PL_16.png", name: "Planning: inhibition of regenerative brake (driver action)", color: "yellow", size: "20×20", areas: ["D2","D3","D4"],
    when: "Forthcoming inhibition of regenerative brake, driver requested to act. " + PL_GROUP_WHEN, ref: "8.3.4.13" },
  { id: "PL17", cat: "pl", file: "PL_17.png", name: "Planning: close air conditioning intake (automatic)", color: "grey", size: "20×20", areas: ["D2","D3","D4"],
    when: "Forthcoming order “close air conditioning intake”, automatic execution. " + PL_GROUP_WHEN, ref: "8.3.4.3" },
  { id: "PL18", cat: "pl", file: "PL_18.png", name: "Planning: open air conditioning intake (automatic)", color: "grey", size: "20×20", areas: ["D2","D3","D4"],
    when: "Forthcoming order “open air conditioning intake”, automatic execution. " + PL_GROUP_WHEN, ref: "8.3.4.4" },
  { id: "PL19", cat: "pl", file: "PL_19.png", name: "Planning: close air conditioning intake (driver action)", color: "yellow", size: "20×20", areas: ["D2","D3","D4"],
    when: "Forthcoming order “close air conditioning intake”, driver requested to act. " + PL_GROUP_WHEN, ref: "8.3.4.3" },
  { id: "PL20", cat: "pl", file: "PL_20.png", name: "Planning: open air conditioning intake (driver action)", color: "yellow", size: "20×20", areas: ["D2","D3","D4"],
    when: "Forthcoming order “open air conditioning intake”, driver requested to act. " + PL_GROUP_WHEN, ref: "8.3.4.4" },
  { id: "PL21", cat: "pl", file: "PL_21.png", name: "Speed profile: speed increase", color: "grey", size: "20×20", areas: ["D6","D7"],
    when: "Marks an MRSP speed increase along the planning distance scale; the new speed value is shown in grey next to it. The bottom of the horizontal line sits at the discontinuity location (left half in D6, right half in D7).", ref: "8.3.6.4" },
  { id: "PL22", cat: "pl", file: "PL_22.png", name: "Speed profile: speed decrease", color: "grey", size: "20×20", areas: ["D6","D7"],
    when: "Marks an MRSP speed decrease (or the EOA/LOA) along the planning distance scale; the new speed value is shown in grey.", ref: "8.3.6.4" },
  { id: "PL23", cat: "pl", file: "PL_23.png", name: "Speed profile: decrease to the indication-marker target", color: "yellow", size: "20×20", areas: ["D6","D7"],
    when: "Marks the speed decrease belonging to the target related to the indication marker; its speed value is shown in yellow. Once Target Speed Monitoring is entered it is replaced by PL22; in Automatic Driving mode PL37 is used instead.", ref: "8.3.6.4, 8.3.8" },
  { id: "PL24", cat: "pl", file: "PL_24.png", name: "Planning: sound horn", color: "yellow", size: "20×20", areas: ["D2","D3","D4"],
    when: "Forthcoming order “sound horn”. " + PL_GROUP_WHEN, ref: "8.3.4.14" },
  { id: "PL25", cat: "pl", file: "PL_25.png", name: "Planning: traction — no traction system (automatic)", color: "grey", size: "20×20", areas: ["D2","D3","D4"],
    when: "Forthcoming change of traction system: “line not fitted with any traction system”, automatic execution. " + PL_GROUP_WHEN, ref: "8.3.4.15" },
  { id: "PL26", cat: "pl", file: "PL_26.png", name: "Planning: traction — no traction system (driver action)", color: "yellow", size: "20×20", areas: ["D2","D3","D4"],
    when: "Forthcoming change of traction system: “line not fitted with any traction system”, driver requested to act. " + PL_GROUP_WHEN, ref: "8.3.4.15" },
  { id: "PL27", cat: "pl", file: "PL_27.png", name: "Planning: traction AC 25 kV 50 Hz (automatic)", color: "grey", size: "20×20", areas: ["D2","D3","D4"],
    when: "Forthcoming change of traction system to AC 25 kV 50 Hz, automatic execution. " + PL_GROUP_WHEN, ref: "8.3.4.16" },
  { id: "PL28", cat: "pl", file: "PL_28.png", name: "Planning: traction AC 25 kV 50 Hz (driver action)", color: "yellow", size: "20×20", areas: ["D2","D3","D4"],
    when: "Forthcoming change of traction system to AC 25 kV 50 Hz, driver requested to act. " + PL_GROUP_WHEN, ref: "8.3.4.16" },
  { id: "PL29", cat: "pl", file: "PL_29.png", name: "Planning: traction AC 15 kV 16.7 Hz (automatic)", color: "grey", size: "20×20", areas: ["D2","D3","D4"],
    when: "Forthcoming change of traction system to AC 15 kV 16.7 Hz, automatic execution. " + PL_GROUP_WHEN, ref: "8.3.4.17" },
  { id: "PL30", cat: "pl", file: "PL_30.png", name: "Planning: traction AC 15 kV 16.7 Hz (driver action)", color: "yellow", size: "20×20", areas: ["D2","D3","D4"],
    when: "Forthcoming change of traction system to AC 15 kV 16.7 Hz, driver requested to act. " + PL_GROUP_WHEN, ref: "8.3.4.17" },
  { id: "PL31", cat: "pl", file: "PL_31.png", name: "Planning: traction DC 3 kV (automatic)", color: "grey", size: "20×20", areas: ["D2","D3","D4"],
    when: "Forthcoming change of traction system to DC 3 kV, automatic execution. " + PL_GROUP_WHEN, ref: "8.3.4.18" },
  { id: "PL32", cat: "pl", file: "PL_32.png", name: "Planning: traction DC 3 kV (driver action)", color: "yellow", size: "20×20", areas: ["D2","D3","D4"],
    when: "Forthcoming change of traction system to DC 3 kV, driver requested to act. " + PL_GROUP_WHEN, ref: "8.3.4.18" },
  { id: "PL33", cat: "pl", file: "PL_33.png", name: "Planning: traction DC 1.5 kV (automatic)", color: "grey", size: "20×20", areas: ["D2","D3","D4"],
    when: "Forthcoming change of traction system to DC 1.5 kV, automatic execution. " + PL_GROUP_WHEN, ref: "8.3.4.19" },
  { id: "PL34", cat: "pl", file: "PL_34.png", name: "Planning: traction DC 1.5 kV (driver action)", color: "yellow", size: "20×20", areas: ["D2","D3","D4"],
    when: "Forthcoming change of traction system to DC 1.5 kV, driver requested to act. " + PL_GROUP_WHEN, ref: "8.3.4.19" },
  { id: "PL35", cat: "pl", file: "PL_35.png", name: "Planning: traction DC 600/750 V (automatic)", color: "grey", size: "20×20", areas: ["D2","D3","D4"],
    when: "Forthcoming change of traction system to DC 600/750 V, automatic execution. " + PL_GROUP_WHEN, ref: "8.3.4.20" },
  { id: "PL36", cat: "pl", file: "PL_36.png", name: "Planning: traction DC 600/750 V (driver action)", color: "yellow", size: "20×20", areas: ["D2","D3","D4"],
    when: "Forthcoming change of traction system to DC 600/750 V, driver requested to act. " + PL_GROUP_WHEN, ref: "8.3.4.20" },
  { id: "PL37", cat: "pl", file: "PL_37.png", name: "Speed profile: decrease to the indication-marker target (AD mode)", color: "white", size: "20×20", areas: ["D6","D7"],
    when: "In Automatic Driving mode this white symbol replaces PL23 for the speed decrease to the target related to the indication marker; its speed value is shown in white.", ref: "8.3.6.4.2" },

  /* ============ NAVIGATION (Table 64) ============ */
  { id: "NA03", cat: "na", file: "NA_03.png", name: "Scale up planning information", color: "grey", size: "12×12", areas: ["D9"], tech: "Touch screen",
    when: "Zoom button of the planning area distance scale (shorter range). Disabled (NA05) if zooming further would not change the display.", ref: "5.3.2.7, 8.3.2" },
  { id: "NA04", cat: "na", file: "NA_04.png", name: "Scale down planning information", color: "grey", size: "12×12", areas: ["D12"], tech: "Touch screen",
    when: "Zoom button of the planning area distance scale (larger range). Disabled (NA06) if it would not change the display.", ref: "5.3.2.7, 8.3.2" },
  { id: "NA05", cat: "na", file: "NA_05.png", name: "Scale up planning information (disabled)", color: "dark grey", size: "12×12", areas: ["D9"], tech: "Touch screen",
    when: "Disabled state of NA03 — shown when the planning scale is already at its minimum range.", ref: "5.3.2.7.7" },
  { id: "NA06", cat: "na", file: "NA_06.png", name: "Scale down planning information (disabled)", color: "dark grey", size: "12×12", areas: ["D12"], tech: "Touch screen",
    when: "Disabled state of NA04 — shown when the planning scale is already at its maximum range.", ref: "5.3.2.7.7" },
  { id: "NA07", cat: "na", file: "NA_07.png", name: "Scale up planning information (soft key)", color: "grey", size: "32×32", areas: [], areaText: "H3 (soft key)", tech: "Soft key",
    when: "Soft-key variant of the planning scale-up button; echoed in D9 by NA03/NA05.", ref: "5.3.2.7, 8.3.x" },
  { id: "NA08", cat: "na", file: "NA_08.png", name: "Scale down planning information (soft key)", color: "grey", size: "32×32", areas: [], areaText: "H2 (soft key)", tech: "Soft key",
    when: "Soft-key variant of the planning scale-down button; echoed in D12 by NA04/NA06.", ref: "5.3.2.7" },
  { id: "NA09", cat: "na", file: "NA_09.png", name: "Scale up planning information (soft key, disabled)", color: "dark grey", size: "32×32", areas: [], areaText: "H3 (soft key)", tech: "Soft key",
    when: "Disabled state of NA07.", ref: "5.3.2.7.7" },
  { id: "NA10", cat: "na", file: "NA_10.png", name: "Scale down planning information (soft key, disabled)", color: "dark grey", size: "32×32", areas: [], areaText: "H2 (soft key)", tech: "Soft key",
    when: "Disabled state of NA08.", ref: "5.3.2.7.7" },
  { id: "NA11", cat: "na", file: "NA_11.png", name: "Close window", color: "grey", size: "32×32", areas: [], areaText: "[Close] button in D/F/G area; H3 (soft key)", tech: "Touch screen / Soft key",
    when: "Closes the current window and returns to the parent window. Present on every non-default window.", ref: "5.3.2.7.1a" },
  { id: "NA12", cat: "na", file: "NA_12.png", name: "Close window (disabled)", color: "dark grey", size: "32×32", areas: [], areaText: "[Close] button in D/F/G area; H3 (soft key)", tech: "Touch screen / Soft key",
    when: "Disabled [Close] button — e.g. while the hour glass (ST05) is displayed and the on-board awaits an answer.", ref: "5.3.2.7.6, 11.7" },
  { id: "NA13", cat: "na", file: "NA_13.png", name: "Scroll up", color: "grey", size: "32×32", areas: ["E10"], areaText: "E10; H5 (soft key)", tech: "Touch screen / Soft key",
    when: "Scrolls up through the list of text messages (or other lists). Down-type button with repeat function.", ref: "5.3.2.7.1f, 8.2.3.4.7" },
  { id: "NA14", cat: "na", file: "NA_14.png", name: "Scroll down", color: "grey", size: "32×32", areas: ["E11"], areaText: "E11; H6 (soft key)", tech: "Touch screen / Soft key",
    when: "Scrolls down through the list of text messages (or other lists). Down-type button with repeat function.", ref: "5.3.2.7.1f, 8.2.3.4.7" },
  { id: "NA15", cat: "na", file: "NA_15.png", name: "Scroll up (disabled)", color: "dark grey", size: "32×32", areas: ["E10"], areaText: "E10; H5 (soft key)", tech: "Touch screen / Soft key",
    when: "Disabled scroll-up — shown when scrolling up would not change the display, and while a text message acknowledgement is pending.", ref: "5.3.2.7.5, 8.2.3.4.8b" },
  { id: "NA16", cat: "na", file: "NA_16.png", name: "Scroll down (disabled)", color: "dark grey", size: "32×32", areas: ["E11"], areaText: "E11; H6 (soft key)", tech: "Touch screen / Soft key",
    when: "Disabled scroll-down — shown when scrolling down would not change the display, and while a text message acknowledgement is pending.", ref: "5.3.2.7.5, 8.2.3.4.8b" },
  { id: "NA17", cat: "na", file: "NA_17.png", name: "Next", color: "grey", size: "32×32", areas: [], areaText: "[Next] button in D/F/G area; H4 (soft key)", tech: "Touch screen / Soft key",
    when: "Selects the next window related to the same topic (e.g. Train data 2/3). Disabled (NA18.2) on the last window.", ref: "5.3.2.7.1c" },
  { id: "NA18", cat: "na", file: "NA_18.png", name: "Previous", color: "grey", size: "32×32", areas: [], areaText: "[Previous] button in D/F/G area; H3 (soft key)", tech: "Touch screen / Soft key",
    when: "Selects the previous window related to the same topic. Disabled (NA19) on the first window.", ref: "5.3.2.7.1d" },
  { id: "NA18.2", cat: "na", file: "NA_18.2.png", name: "Next (disabled)", color: "dark grey", size: "32×32", areas: [], areaText: "[Next] button in D/F/G area; H4 (soft key)", tech: "Touch screen / Soft key",
    when: "Disabled state of the [Next] button.", ref: "5.3.2.7.7" },
  { id: "NA19", cat: "na", file: "NA_19.png", name: "Previous (disabled)", color: "dark grey", size: "32×32", areas: [], areaText: "[Previous] button in D/F/G area; H3 (soft key)", tech: "Touch screen / Soft key",
    when: "Disabled state of the [Previous] button.", ref: "5.3.2.7.7" },
  { id: "NA20", cat: "na", file: "NA_20.png", name: "Enter", color: "grey", size: "32×32", areas: [], areaText: "H7 (soft key)", tech: "Soft key",
    when: "Accepts the input field data value (soft key technology). Becomes a delay-type button if an operational data check rule is not satisfied.", ref: "5.3.2.7.1b, 5.3.2.7.3" },
  { id: "NA21", cat: "na", file: "NA_21.png", name: "Delete", color: "grey", size: "32×32", areas: [], areaText: "Key 10 of the dedicated keyboard; H2 (soft key)", tech: "Touch screen / Soft key",
    when: "Deletes the last entered character in a data entry window. Down-type button with repeat function.", ref: "5.3.2.7.1e, 5.3.2.7.2" },
  { id: "NA22", cat: "na", file: "NA_22.png", name: "Enter (disabled)", color: "dark grey", size: "32×32", areas: [], areaText: "H7 (soft key)", tech: "Soft key",
    when: "Disabled state of the [Enter] soft key.", ref: "5.3.2.7.6, 5.3.2.7.7" },
  { id: "NA23", cat: "na", file: "NA_23.png", name: "More", color: "grey", size: "32×32", areas: [], areaText: "Key 12 of the dedicated keyboard; F10 (touch); soft key", tech: "Touch screen / Soft key",
    when: "Presents the next predefined choices of a dedicated keyboard, or the next selections of a menu window.", ref: "5.3.2.7.1i" },

  /* ============ SETTINGS (Table 65) ============ */
  { id: "SE01", cat: "se", file: "SE_01.png", name: "Luminance adjustment", color: "grey", size: "32×32", areas: [], areaText: "Button #3 in the Settings window (D/F/G area)", tech: "Touch screen",
    when: "Opens the luminance adjustment from the Settings window.", ref: "11.2.5 (Settings window)" },
  { id: "SE02", cat: "se", file: "SE_02.png", name: "Volume adjustment", color: "grey", size: "32×32", areas: [], areaText: "Button #2 in the Settings window (D/F/G area)", tech: "Touch screen",
    when: "Opens the volume adjustment from the Settings window.", ref: "11.2.5 (Settings window)" },
  { id: "SE03", cat: "se", file: "SE_03.png", name: "Language selection", color: "grey", size: "32×32", areas: [], areaText: "Button #1 in the Settings window (D/F/G area)", tech: "Touch screen",
    when: "Opens the language selection from the Settings window.", ref: "11.2.5, 5.5" },
  { id: "SE04", cat: "se", file: "SE_04.png", name: "Settings menu", color: "grey", size: "32×32", areas: ["F5"], areaText: "F5; [Settings] button in D/F/G area; H6 (soft key)",
    when: "Opens the Settings menu. Also shown on the Driver ID window during step S1 of the start-up dialogue sequence.", ref: "9.x, 11.3.1, 11.7 (S1)" },

  /* ============ DRIVER REQUEST (Table 66) ============ */
  { id: "DR01", cat: "dr", file: "DR_01.png", name: "Toggle speed/distance information", color: "grey", size: "32×32", areas: ["F7"], areaText: "F7 (soft key)", tech: "Soft key",
    when: "Soft key to toggle the display of the distance-to-target digital value (and related speed/distance info) in OS and SR modes, where it is hidden by default.", ref: "8.2.2.4" },
  { id: "DR02", cat: "dr", file: "DR_02.png", name: "Track Ahead Free", color: "grey with dark grey", size: "75×46", areas: ["D"], areaText: "Question box overlaying area D",
    when: "Shown when trackside (RBC) asks the driver whether the track ahead is free. Presented as a question box with a “Yes” answer button; the driver confirms only if the track ahead of the train is visibly free.", ref: "8.2.3.3" },
  { id: "DR03", cat: "dr", file: "DR_03.png", name: "Geographical position", color: "grey", size: "32×32", areas: ["G12"], areaText: "G12 (touch); F8 (soft key)",
    when: "Shown when the geographical position display is toggled OFF and the position is known by the on-board — pressing it toggles the kilometre position display on (then G12 shows the position in black on grey). Not shown at all if the position is unknown.", ref: "8.4.4" },
  { id: "DR04", cat: "dr", file: "DR_04.png", name: "Acknowledgement (soft key)", color: "yellow", size: "32×32", areas: [], areaText: "H7 (soft key)", tech: "Soft key",
    when: "Soft-key acknowledge button: shown on H7 whenever something on the display requires acknowledgement (mode/level acks in C1, brake interventions, text messages…).", ref: "5.4" },
  { id: "DR05", cat: "dr", file: "DR_05.png", name: "Toggle tunnel stopping area", color: "grey", size: "32×32", areas: ["C2","C3","C4"], areaText: "C2/C3/C4 (touch); F6 (soft key)",
    when: "Shown when the tunnel stopping area display is toggled OFF and tunnel stopping areas are known by the on-board; pressing it toggles the display on (then TC36/TC37 appear in C2). Not shown if no tunnel stopping areas are known.", ref: "8.2.3.6" },

  /* ============ LEVEL CROSSING (Table 67) ============ */
  { id: "LX01", cat: "lx", file: "LX_01.png", name: "Level crossing not protected", color: "grey", size: "32×32", areas: ["B3","B4","B5"],
    when: "Shown when the train approaches/passes a level crossing that is not protected — the driver must apply the applicable operational rules (typically proceed on sight over the crossing).", ref: "8.2.3.8" },

  /* ============ LIMITED SUPERVISION (Table 67a) ============ */
  { id: "LS01", cat: "ls", file: "LS_01.png", name: "Limited Supervision frame (LSSMA)", color: "grey", size: "50×50", areas: ["A1"],
    when: "Shown in A1 whenever the LSSMA (Lowest Supervised Speed within the Movement Authority) number is displayed in Limited Supervision mode; the number overlays this frame. It signals that the speed is specific to LS mode and does not replace observation of line-side signals.", ref: "8.2.1.7" },

  /* ============ ATO (Table 67b) ============ */
  { id: "ATO01", cat: "ato", file: "ATO_01.png", name: "ATO selected", color: "grey", size: "45×45", areas: ["G1"],
    when: "ATO status “selected”: ATO is selected on this train but the engagement conditions are not yet fulfilled.", ref: "8.5.2" },
  { id: "ATO02", cat: "ato", file: "ATO_02.png", name: "ATO ready for engagement", color: "yellow", size: "45×45", areas: ["G1","F9"],
    when: "ATO status “ready for engagement”: all conditions are fulfilled — G1 (touch) or F9 (soft key) becomes the ATO engage button the driver can press.", ref: "8.5.2.5, 8.5.2.7" },
  { id: "ATO03", cat: "ato", file: "ATO_03.png", name: "ATO engaged", color: "white", size: "45×45", areas: ["G1","F9"],
    when: "ATO status “engaged”: the train is driven automatically (mode AD, see MO23). G1/F9 acts as the disengage button.", ref: "8.5.2.6, 8.5.2.8" },
  { id: "ATO04", cat: "ato", file: "ATO_04.png", name: "ATO disengaging", color: "red with grey", size: "45×45", areas: ["G1","F9"],
    when: "ATO status “disengaging”: ATO is in the process of being disengaged; the driver must take over.", ref: "8.5.2" },
  { id: "ATO05", cat: "ato", file: "ATO_05.png", name: "ATO failure", color: "red with grey", size: "45×45", areas: ["G1"],
    when: "ATO status “failure”: the ATO on-board has failed.", ref: "8.5.2" },
  { id: "ATO06", cat: "ato", file: "ATO_06.png", name: "Overshoot stopping window", color: "yellow", size: "45×45", areas: ["G2"],
    when: "After stopping at a stopping point: the train has overshot the stopping window — the driver is requested to act (per operational rules).", ref: "8.5.4.3" },
  { id: "ATO07", cat: "ato", file: "ATO_07.png", name: "Undershoot stopping window", color: "yellow", size: "45×45", areas: ["G2"],
    when: "After stopping at a stopping point: the train has undershot the stopping window — the driver is requested to act.", ref: "8.5.4.4" },
  { id: "ATO08", cat: "ato", file: "ATO_08.png", name: "Inside stopping window (accurate stop)", color: "grey", size: "45×45", areas: ["G2"],
    when: "The ATO has achieved an accurate stop inside the stopping window.", ref: "8.5.4.5" },
  { id: "ATO09", cat: "ato", file: "ATO_09.png", name: "Train hold", color: "grey", size: "45×45", areas: ["G3"],
    when: "Shown when the ERTMS/ATO on-board requests to display “Train hold” — the train is held at the stopping point (otherwise G3 shows the remaining dwell time).", ref: "8.5.5.7" },
  { id: "ATO10", cat: "ato", file: "ATO_10.png", name: "Open doors on both sides", color: "yellow", size: "45×45", areas: ["G4"],
    when: "Door information at a stopping point: the driver is requested to open the doors on both sides.", ref: "8.5.6.3" },
  { id: "ATO11", cat: "ato", file: "ATO_11.png", name: "Open doors on the left", color: "yellow", size: "45×45", areas: ["G4"],
    when: "Door information: the driver is requested to open the doors on the left side.", ref: "8.5.6.3" },
  { id: "ATO12", cat: "ato", file: "ATO_12.png", name: "Open doors on the right", color: "yellow", size: "45×45", areas: ["G4"],
    when: "Door information: the driver is requested to open the doors on the right side.", ref: "8.5.6.3" },
  { id: "ATO13", cat: "ato", file: "ATO_13.png", name: "Doors are open", color: "grey", size: "45×45", areas: ["G4"],
    when: "Door information: the doors are open.", ref: "8.5.6.3" },
  { id: "ATO14", cat: "ato", file: "ATO_14.png", name: "Close doors", color: "yellow", size: "45×45", areas: ["G4"],
    when: "Door information: the driver is requested to close the doors.", ref: "8.5.6.3" },
  { id: "ATO15", cat: "ato", file: "ATO_15.png", name: "Doors being closed by ATO", color: "grey", size: "45×45", areas: ["G4"],
    when: "Door information: the doors are being closed automatically by ATO.", ref: "8.5.6.3" },
  { id: "ATO16", cat: "ato", file: "ATO_16.png", name: "Doors are closed", color: "grey", size: "45×45", areas: ["G4"],
    when: "Door information: the doors are closed.", ref: "8.5.6.3" },
  { id: "ATO17", cat: "ato", file: "ATO_17.png", name: "Skip stopping point — inactive", color: "grey", size: "45×45", areas: ["G5","F10"],
    when: "Skip stopping point status “inactive”. G5 (touch) / F10 (soft key) is a delay-type button with which the driver can request skipping the next stopping point.", ref: "8.5.8.4, 8.5.8.5" },
  { id: "ATO18", cat: "ato", file: "ATO_18.png", name: "Skip stopping point — requested by ATO-TS", color: "grey", size: "45×45", areas: ["G5"],
    when: "Skip stopping point requested by the ATO trackside.", ref: "8.5.8.4" },
  { id: "ATO19", cat: "ato", file: "ATO_19.png", name: "Skip stopping point — requested by driver", color: "white", size: "45×45", areas: ["G5","F10"],
    when: "Skip stopping point requested by the driver; pressing the (delay-type) button again revokes the request.", ref: "8.5.8.4, 8.5.8.5" },
  { id: "ATO20", cat: "ato", file: "ATO_20.png", name: "Coasting advice", color: "grey", size: "32×32", areas: ["B8"],
    when: "Driving advice to coast (no traction needed to keep the schedule). Shown in B8 above the speed dial.", ref: "8.5.10.3" },
  { id: "ATO21", cat: "ato", file: "ATO_21.png", name: "Stopping point", color: "grey", size: "20×20", areas: ["D2","D3","D4"],
    when: "Marks the ATO stopping points ahead of the train in the planning area, at their scaled distance, within the movement authority up to the first zero-speed target.", ref: "8.5.3" },

  /* ============ SUPERVISED MANOEUVRE (Table 67c) ============ */
  { id: "SM01", cat: "sm", file: "SM01.png", name: "SM authorised direction — forward", color: "grey", size: "32×32", areas: ["B8"],
    when: "Shown in B8 while in Supervised Manoeuvre mode (with MO24 in B7): movement authorised in the forward direction. The Sinfo sound is played when the authorised direction changes.", ref: "8.2.3.10" },
  { id: "SM02", cat: "sm", file: "SM02.png", name: "SM authorised direction — backward", color: "grey", size: "32×32", areas: ["B8"],
    when: "Shown in B8 while in Supervised Manoeuvre mode (with MO24 in B7): movement authorised in the backward direction. The Sinfo sound is played when the authorised direction changes.", ref: "8.2.3.10" }
];

/* ---------- Relations between symbols ----------
   t: gy   = grey (automatic/state) vs yellow (driver action) variant
      ack  = mode and its acknowledgement
      lvl  = level and its announcement(s)
      plan = same order: B-area symbol vs planning-area miniature
      dis  = enabled vs disabled button
      tech = touch screen vs soft key variant
      fam  = same functional family
      ctx  = related function elsewhere on the DMI */
const RELATIONS = [
  /* grey / yellow variants */
  { t: "gy", ids: ["TC02","TC03"] }, { t: "gy", ids: ["TC04","TC05"] }, { t: "gy", ids: ["TC06","TC07"] },
  { t: "gy", ids: ["TC08","TC09"] }, { t: "gy", ids: ["TC10","TC11"] }, { t: "gy", ids: ["TC13","TC14"] },
  { t: "gy", ids: ["TC15","TC16"] }, { t: "gy", ids: ["TC17","TC18"] }, { t: "gy", ids: ["TC19","TC21"] },
  { t: "gy", ids: ["TC20","TC22"] }, { t: "gy", ids: ["TC23","TC24"] }, { t: "gy", ids: ["TC25","TC26"] },
  { t: "gy", ids: ["TC27","TC28"] }, { t: "gy", ids: ["TC29","TC30"] }, { t: "gy", ids: ["TC31","TC32"] },
  { t: "gy", ids: ["TC33","TC34"] }, { t: "gy", ids: ["TC36","TC37"] },
  { t: "gy", ids: ["LE06","LE07"] }, { t: "gy", ids: ["LE08","LE09"] },
  { t: "gy", ids: ["PL01","PL02"] }, { t: "gy", ids: ["PL03","PL04"] }, { t: "gy", ids: ["PL05","PL06"] },
  { t: "gy", ids: ["PL07","PL08"] }, { t: "gy", ids: ["PL11","PL12"] }, { t: "gy", ids: ["PL13","PL14"] },
  { t: "gy", ids: ["PL15","PL16"] }, { t: "gy", ids: ["PL17","PL19"] }, { t: "gy", ids: ["PL18","PL20"] },
  { t: "gy", ids: ["PL25","PL26"] }, { t: "gy", ids: ["PL27","PL28"] }, { t: "gy", ids: ["PL29","PL30"] },
  { t: "gy", ids: ["PL31","PL32"] }, { t: "gy", ids: ["PL33","PL34"] }, { t: "gy", ids: ["PL35","PL36"] },
  /* mode and its acknowledgement */
  { t: "ack", ids: ["MO01","MO02"] }, { t: "ack", ids: ["MO04","MO05"] }, { t: "ack", ids: ["MO07","MO08"] },
  { t: "ack", ids: ["MO09","MO10"] }, { t: "ack", ids: ["MO14","MO15"] }, { t: "ack", ids: ["MO16","MO17"] },
  { t: "ack", ids: ["MO19","MO20"] }, { t: "ack", ids: ["MO21","MO22"] },
  /* level and its announcements */
  { t: "lvl", ids: ["LE01","LE06","LE07"] }, { t: "lvl", ids: ["LE02","LE08","LE09"] },
  { t: "lvl", ids: ["LE03","LE10"] }, { t: "lvl", ids: ["LE04","LE12"] },
  /* B-area symbol vs planning miniature */
  { t: "plan", ids: ["TC02","TC03","PL01","PL02"] }, { t: "plan", ids: ["TC04","TC05","PL03","PL04"] },
  { t: "plan", ids: ["TC06","TC07","PL05","PL06"] }, { t: "plan", ids: ["TC08","TC09","PL07","PL08"] },
  { t: "plan", ids: ["TC11","PL09"] }, { t: "plan", ids: ["TC12","PL10"] },
  { t: "plan", ids: ["TC13","TC14","PL11","PL12"] }, { t: "plan", ids: ["TC15","TC16","PL13","PL14"] },
  { t: "plan", ids: ["TC17","TC18","PL15","PL16"] }, { t: "plan", ids: ["TC19","TC21","PL17","PL19"] },
  { t: "plan", ids: ["TC20","TC22","PL18","PL20"] }, { t: "plan", ids: ["TC35","PL24"] },
  { t: "plan", ids: ["TC23","TC24","PL25","PL26"] }, { t: "plan", ids: ["TC25","TC26","PL27","PL28"] },
  { t: "plan", ids: ["TC27","TC28","PL29","PL30"] }, { t: "plan", ids: ["TC29","TC30","PL31","PL32"] },
  { t: "plan", ids: ["TC31","TC32","PL33","PL34"] }, { t: "plan", ids: ["TC33","TC34","PL35","PL36"] },
  /* enabled vs disabled buttons */
  { t: "dis", ids: ["NA03","NA05"] }, { t: "dis", ids: ["NA04","NA06"] }, { t: "dis", ids: ["NA07","NA09"] },
  { t: "dis", ids: ["NA08","NA10"] }, { t: "dis", ids: ["NA11","NA12"] }, { t: "dis", ids: ["NA13","NA15"] },
  { t: "dis", ids: ["NA14","NA16"] }, { t: "dis", ids: ["NA17","NA18.2"] }, { t: "dis", ids: ["NA18","NA19"] },
  { t: "dis", ids: ["NA20","NA22"] },
  /* touch screen vs soft key */
  { t: "tech", ids: ["NA03","NA07"] }, { t: "tech", ids: ["NA04","NA08"] },
  /* functional families */
  { t: "fam", ids: ["ATO01","ATO02","ATO03","ATO04","ATO05"] },
  { t: "fam", ids: ["ATO06","ATO07","ATO08"] },
  { t: "fam", ids: ["ATO10","ATO11","ATO12","ATO13","ATO14","ATO15","ATO16"] },
  { t: "fam", ids: ["ATO17","ATO18","ATO19"] },
  { t: "fam", ids: ["PL21","PL22","PL23","PL37"] },
  { t: "fam", ids: ["SM01","SM02"] },
  { t: "fam", ids: ["ST03","ST04"] },
  /* related function */
  { t: "ctx", ids: ["MO23","ATO03"] }, { t: "ctx", ids: ["MO24","SM01","SM02"] },
  { t: "ctx", ids: ["MO14","MO15","ST06"] }, { t: "ctx", ids: ["MO21","LS01"] },
  { t: "ctx", ids: ["DR05","TC36","TC37"] }, { t: "ctx", ids: ["ST01","MO04"] }
];

/* ---------------------------------------------------------------------------
 * Chapter 15 — system status messages (Tables 68, 69, 70).
 * table: 68 = SUBSET-026 related, 69 = SUBSET-035 (NTC/STM), 70 = SUBSET-125 (ATO).
 * Start/end condition references are clauses of the respective SUBSET.
 * r = "Table 4.7.2 corresponding row" (SUBSET-026), i.e. why/under which
 * mode-dependent rule the message is shown.
 * ack: displayed as a text message TO BE acknowledged (15.1.1.4.1).
 * --------------------------------------------------------------------------- */
const MSG_E30 = "Message displayed for 30 s";
const MSG_E30_STANDSTILL = "Message displayed for 30 s once standstill brake-revocation condition § 3.14.1.6 is fulfilled";
const MSG_EPT = "PT mode left, or trip acknowledged/revoked (§ 4.6.3 [62] / [63])";
const MSG_EPT68 = "PT mode left, or § 4.6.3 [62] / [63] / [68]";
const MSG_EBTN = "As soon as any button in the main window is selected";
const MSG_ERADIO = "Driver elects to perform the mission with only one radio system, or any button in the main window is selected";

const MESSAGES = [
  { text: "Balise read error", table: 68,
    meaning: "The onboard detected a balise transmission/linking inconsistency. Depending on the case it commands a service brake (message explains the brake reason) or even a train trip.",
    rows: [
      { s: "§ 3.16.2.4.4.3", e: MSG_E30_STANDSTILL, r: "Brake reason" },
      { s: "§ 3.16.2.5.3", e: MSG_E30_STANDSTILL, r: "Brake reason" },
      { s: "§ 3.16.2.6.1 (service brake reaction)", e: MSG_E30_STANDSTILL, r: "Brake reason" },
      { s: "§ 3.16.2.7.1.1", e: MSG_E30_STANDSTILL, r: "Brake reason" },
      { s: "§ 3.16.2.7.2.2", e: MSG_E30_STANDSTILL, r: "Brake reason" },
      { s: "§ 4.6.3 [17]", e: MSG_EPT68, r: "Trip reason" },
      { s: "§ 4.6.3 [66]", e: MSG_EPT68, r: "Trip reason" }
    ] },
  { text: "Trackside malfunction", table: 68,
    meaning: "A malfunction of the trackside equipment was detected (e.g. a balise group telegram that should have been received was not).",
    rows: [ { s: "§ 3.16.2.4.9", e: MSG_E30, r: "Trackside malfunction" } ] },
  { text: "Communication error", table: 68,
    meaning: "The radio communication session with the RBC was lost or disturbed; the onboard applied the service brake or, in the worst case, tripped the train.",
    rows: [
      { s: "§ 3.16.3.4.1 (service brake reaction)", e: "Displayed 30 s (after standstill condition § 3.14.1.7, or after brake command reason revoked per § 4.12.1.2)", r: "Brake reason" },
      { s: "§ 4.6.3 [41]", e: MSG_EPT, r: "Trip reason" }
    ] },
  { text: "Entering FS", table: 68,
    meaning: "Announces that the train is about to enter Full Supervision mode (the onboard has received an MA with full track description).",
    rows: [ { s: "§ 4.4.9.1.4", e: "§ 4.4.9.1.4", r: "Entry in FS" } ] },
  { text: "Entering OS", table: 68,
    meaning: "Announces that the train is about to enter On Sight mode.",
    rows: [ { s: "§ 4.4.12.1.7", e: "§ 4.4.12.1.7", r: "Entry in OS" } ] },
  { text: "Entering SM", table: 68,
    meaning: "Announces that the train is about to enter Supervised Manoeuvre mode.",
    rows: [ { s: "§ 4.4.21.1.6", e: "§ 4.4.21.1.6", r: "Entry in SM" } ] },
  { text: "Runaway movement", table: 68,
    meaning: "The train moved in a different direction than the one permitted/supervised — the onboard commanded the emergency brake. Shown to explain the brake reason.",
    rows: [
      { s: "§ 3.14.2.4", e: "§ 3.14.1.5", r: "Brake reason" },
      { s: "§ 3.14.3.2", e: "§ 3.14.1.5", r: "Brake reason" },
      { s: "§ 3.14.4.2 and § 3.14.4.5", e: "§ 3.14.1.5", r: "Brake reason" },
      { s: "§ 3.18.3.3.1", e: "§ 3.14.1.5", r: "Brake reason" },
      { s: "§ 4.4.11.1.5.1", e: "§ 3.14.1.5", r: "Brake reason" }
    ] },
  { text: "SM refused", table: 68,
    meaning: "The RBC refused the request for Supervised Manoeuvre.",
    rows: [ { s: "§ 5.21.2 A220", e: MSG_EBTN, r: "Supervised Manoeuvre request refused by RBC" } ] },
  { text: "SM request failed", table: 68,
    meaning: "The Supervised Manoeuvre request was not answered by the RBC in time.",
    rows: [ { s: "§ 5.21.4.1", e: MSG_EBTN, r: "Supervised Manoeuvre request not answered by RBC" } ] },
  { text: "SH refused", table: 68,
    meaning: "The RBC refused the request for Shunting; if the train passes a 'stop if in SH' related condition while tripped, it is also shown as the trip reason.",
    rows: [
      { s: "§ 5.6.2 A220", e: MSG_EBTN, r: "Shunting refused by RBC" },
      { s: "§ 4.6.3 [35]", e: "§ 4.6.3 [63]", r: "Trip reason" }
    ] },
  { text: "SH request failed", table: 68,
    meaning: "The Shunting request was not answered by the RBC in time.",
    rows: [ { s: "§ 5.6.4.1.2", e: MSG_EBTN, r: "Shunting request not answered by RBC" } ] },
  { text: "Trackside not compatible", table: 68,
    meaning: "The trackside operates a system version that is not compatible with the onboard — the train cannot be supervised on this line.",
    rows: [
      { s: "§ 3.5.3.7 d) 2nd bullet", e: MSG_E30, r: "Trackside not compatible" },
      { s: "§ 4.6.3 [65]", e: MSG_EPT68, r: "Trip reason" }
    ] },
  { text: "Train data changed", table: 68,
    meaning: "Train data were changed by a source other than the driver (e.g. automatically from the train). Depending on the situation it may also explain a brake application.",
    rows: [
      { s: "§ 5.17.2.2 A1", e: "Displayed 30 s from the time a train movement is detected", r: "Notification of Train Data change from source different from the driver" },
      { s: "§ 5.17.2.2 S2", e: "§ 5.17.2.2 S3 (E3)", r: "Brake reason" },
      { s: "§ 5.17.2.2 S4", e: "§ 5.17.2.2 S5 (E5)", r: "Brake reason" }
    ] },
  { text: "Safe consist length no longer available", table: 68,
    meaning: "During Supervised Manoeuvre the safe train length information became unavailable — the onboard commands the brake.",
    rows: [ { s: "§ 4.4.21.1.12", e: "Displayed 30 s (after § 3.14.1.7.6, or after brake command reason revoked per § 4.12.1.2)", r: "Brake reason" } ] },
  { text: "Train is rejected", table: 68,
    meaning: "The RBC rejected the train during Start of Mission.",
    rows: [ { s: "§ 5.4.3.2 A40", e: MSG_EBTN, r: "Train is rejected" } ] },
  { text: "Unauthorized passing of EOA / LOA", table: 68,
    meaning: "The train passed the End of Authority / Limit of Authority without authorisation — the train was tripped. Shown in Post Trip as the trip reason.",
    rows: [
      { s: "§ 4.6.3 [11]", e: MSG_EPT, r: "Trip reason" },
      { s: "§ 4.6.3 [12]", e: MSG_EPT, r: "Trip reason" },
      { s: "§ 4.6.3 [16]", e: MSG_EPT, r: "Trip reason" },
      { s: "§ 4.6.3 [18]", e: MSG_EPT, r: "Trip reason" },
      { s: "§ 4.6.3 [43]", e: MSG_EPT, r: "Trip reason" }
    ] },
  { text: "No MA received at level transition", table: 68,
    meaning: "The train passed a level transition border without having received a Movement Authority for the new level — the train was tripped.",
    rows: [
      { s: "§ 4.6.3 [39]", e: MSG_EPT, r: "Trip reason" },
      { s: "§ 4.6.3 [67]", e: MSG_EPT, r: "Trip reason" }
    ] },
  { text: "SR distance exceeded", table: 68,
    meaning: "The permitted distance to run in Staff Responsible was exceeded — the train was tripped.",
    rows: [ { s: "§ 4.6.3 [42]", e: MSG_EPT, r: "Trip reason" } ] },
  { text: "SH stop order", table: 68,
    meaning: "A 'stop if in Shunting' order was received from the trackside while the train was in SH — the train was tripped.",
    rows: [
      { s: "§ 4.6.3 [49]", e: "PT mode left, or § 4.6.3 [68]", r: "Trip reason" },
      { s: "§ 4.6.3 [52]", e: "PT mode left, or § 4.6.3 [68]", r: "Trip reason" }
    ] },
  { text: "SR stop order", table: 68,
    meaning: "A 'stop if in Staff Responsible' order was received from a balise group while the train was in SR — the train was tripped.",
    rows: [
      { s: "§ 4.6.3 [36]", e: MSG_EPT, r: "Trip reason" },
      { s: "§ 4.6.3 [54] (if operated system version X ≥ 2)", e: MSG_EPT, r: "Trip reason" },
      { s: "§ 6.6.2.2.2 (if operated system version X = 1)", e: MSG_EPT, r: "Trip reason" }
    ] },
  { text: "Emergency stop", table: 68,
    meaning: "An unconditional emergency stop was received from the RBC — the train was tripped.",
    rows: [ { s: "§ 4.6.3 [20]", e: MSG_EPT, r: "Trip reason" } ] },
  { text: "RV distance exceeded", table: 68,
    meaning: "The permitted distance to run in Reversing was exceeded — the onboard commands the brake.",
    rows: [
      { s: "§ 3.15.4.8", e: "§ 3.14.1.7.1", r: "Brake reason" },
      { s: "§ 4.4.18.1.4", e: "§ 3.14.1.7.1", r: "Brake reason" }
    ] },
  { text: "PT distance exceeded", table: 68,
    meaning: "The permitted backwards movement distance in Post Trip was exceeded — the onboard commands the brake.",
    rows: [
      { s: "§ 4.4.14.1.3", e: "§ 3.14.1.7.4", r: "Brake reason" },
      { s: "§ 4.4.14.1.3.2", e: "§ 3.14.1.7.4", r: "Brake reason" }
    ] },
  { text: "No track description", table: 68,
    meaning: "No track description is available where it is required — the train was tripped.",
    rows: [ { s: "§ 4.6.3 [69]", e: MSG_EPT, r: "Trip reason" } ] },
  { text: "[name of NTC] brake demand", table: 68,
    meaning: "The national system (NTC) demanded a brake application that led to a train trip. '[name of NTC]' is replaced by the abbreviation of the concerned national system.",
    rows: [ { s: "§ 4.6.3 [38]", e: MSG_EPT, r: "Trip reason" } ] },
  { text: "Route unsuitable – loading gauge", table: 68,
    meaning: "The route ahead is unsuitable for the train's loading gauge.",
    rows: [ { s: "§ 3.12.2.3 a)", e: "Route suitability data deleted (A.3.4, § 3.7.3.2 d), or § 3.7.3.1 h) with § 3.12.2.3 a) not fulfilled)", r: "Route unsuitability(ies)" } ] },
  { text: "Route unsuitable – traction system", table: 68,
    meaning: "The route ahead is unsuitable for the train's traction system.",
    rows: [ { s: "§ 3.12.2.3 b)", e: "Route suitability data deleted (A.3.4, § 3.7.3.2 d), or § 3.7.3.1 i) with § 3.12.2.3 b) not fulfilled)", r: "Route unsuitability(ies)" } ] },
  { text: "Route unsuitable – axle load category", table: 68,
    meaning: "The route ahead is unsuitable for the train's axle load category.",
    rows: [ { s: "§ 3.12.2.3 c)", e: "Route suitability data deleted (A.3.4, § 3.7.3.2 d), or § 3.7.3.1 j) with § 3.12.2.3 c) not fulfilled)", r: "Route unsuitability(ies)" } ] },
  { text: "FRMCS network registration failed", table: 68,
    meaning: "Registration to the FRMCS radio network failed during Start of Mission.",
    rows: [
      { s: "§ 5.4.3.2 A41", e: MSG_ERADIO, r: "Failed Radio Network registration(s)" },
      { s: "§ 5.4.3.2 A42", e: MSG_ERADIO, r: "Failed Radio Network registration(s)" },
      { s: "§ 5.4.3.2 A43", e: MSG_ERADIO, r: "Failed Radio Network registration(s)" }
    ] },
  { text: "GSM-R network registration failed", table: 68,
    meaning: "Registration to the GSM-R radio network failed during Start of Mission.",
    rows: [
      { s: "§ 5.4.3.2 A29", e: MSG_ERADIO, r: "Failed Radio Network registration(s)" },
      { s: "§ 5.4.3.2 A42", e: MSG_ERADIO, r: "Failed Radio Network registration(s)" },
      { s: "§ 5.4.3.2 A43", e: MSG_ERADIO, r: "Failed Radio Network registration(s)" }
    ] },
  { text: "NL no longer permitted", table: 68, ack: true,
    meaning: "Non Leading mode is no longer permitted (the conditions for NL ended). One of only two system status messages that must be acknowledged by the driver.",
    rows: [ { s: "§ 4.4.15.1.1.3", e: "Text acknowledged", r: "Non-leading no longer permitted" } ] },
  { text: "Odometer impaired", table: 68,
    meaning: "The odometry accuracy is impaired — the accumulated under/over-estimation of the measured movement over a defined total distance exceeded the limit.",
    rows: [ { s: "§ 3.6.8.5", e: "§ 3.6.8.6", r: "Odometer accuracy impairment" } ] },

  /* Table 69 — SUBSET-035 (NTC / STM) */
  { text: "[name of NTC] is not available", table: 69,
    meaning: "The selected national system (NTC) is not available on board.",
    rows: [ { s: "§ 10.3.3.8", e: "§ 10.3.3.8", r: "NTC not available" } ] },
  { text: "[name of NTC] needs data", table: 69,
    meaning: "The national system (NTC) needs specific data to be entered by the driver.",
    rows: [ { s: "§ 10.7.3.4", e: "§ 10.7.3.5", r: "NTC data need" } ] },
  { text: "Runaway movement", table: 69,
    meaning: "Runaway movement detected and braked while a national system (NTC/STM) is in charge of the supervision.",
    rows: [ { s: "§ 10.7.3.9", e: "§ 10.7.3.9", r: "Brake reason" } ] },
  { text: "[name of NTC] failed", table: 69, ack: true,
    meaning: "The national system (NTC) failed. Displayed as a text message that must be acknowledged by the driver.",
    rows: [
      { s: "§ 10.14.1.1", e: "Text acknowledged", r: "NTC failed" },
      { s: "§ 10.14.1.2", e: "Text acknowledged", r: "NTC failed" }
    ] },

  /* Table 70 — SUBSET-125 (ATO) */
  { text: "ATO needs data", table: 70,
    meaning: "The Automatic Train Operation onboard needs specific data to be entered by the driver.",
    rows: [ { s: "§ 7.14.2.13", e: "§ 7.14.2.14", r: "ATO data need" } ] },
  { text: "Runaway movement", table: 70,
    meaning: "Runaway movement detected and braked while ATO is engaged.",
    rows: [ { s: "§ 7.14.2.18", e: "§ 7.14.2.18", r: "Brake reason" } ] }
];

/* Which SUBSET the start/end clause references of each table point to. */
const MSG_TABLES = {
  68: "SUBSET-026",
  69: "SUBSET-035",
  70: "SUBSET-125"
};
